//
//  TypstCodeView.swift
//  FeynmanSketchMac
//
//  Created by HEEDER Ewan on 20/08/2026.
//

import SwiftUI
import AppKit

/// A side panel displaying the generated Typst source code, with options to copy it or dismiss the panel.
struct TypstCodeView: View {
    /// The typst code to display. Regenerated by the toolbar's "Generate" button, not live updated.
    let code: String
    
    /// Whether this panel is shown. Set to `false` to dismiss it.
    @Binding var isVisible: Bool
    
    var body: some View {
        VStack(alignment: .center) {
            // The code area, scrollable.
            ScrollView {
                Text(code)
                    .font(.system(.body, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }
            .background(Color.black.opacity(0.15))
            .clipShape(RoundedRectangle(cornerRadius: 8))
            .padding()
            
            // Copy code
            Button {
                NSPasteboard.general.clearContents()
                NSPasteboard.general.setString(code, forType: .string)
            } label: {
                Image(systemName: "doc.on.clipboard")
            }
            .help("Copy code")
            .padding(.bottom)
            
            // Dismiss panel.
            Button {
                isVisible = false
            } label: {
                Text("Hide panel")
            }
            .padding(.bottom)
        }
        .frame(width: 320)
        .background(Color.gray.opacity(0.15))
    }
}
